name: Publish to PyPI

on:
  release:
    types: [published]

  workflow_run:
    workflows: ["Create Release"] # Must match the 'name' in release.yml
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    # Only run if the release workflow actually succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    environment:
      name: pypi
      url: https://pypi.org/p/txtflar
    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          # This is required when using workflow_run to find artifacts from the trigger
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # This action automatically looks in the dist/ folder
          packages-dir: dist/
